package hue.captains.singapura.js.homing.ui.specimens;

import hue.captains.singapura.js.homing.core.DomModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleImports;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.stream.Collectors;

/**
 * The house's specimens, as a page looks them up: {@code HOUSE_SPECIMENS[leaf]} is the class that
 * builds a leaf live, by the leaf's token; {@code HOUSE_PENDING} the realized leaves whose
 * specimens are still to come, and {@code HOUSE_UNREALIZED} those nothing realizes yet. Generated
 * from {@link HouseSpecimens}, each class imported from the module that exports it, so no second
 * list can drift from it.
 *
 * <p>A {@code DomModule}, though it touches no DOM: a plain module's imports are served without
 * the page's theme, so the specimens it imports - and the parties and the steward they import -
 * would load a second time.</p>
 *
 * <p>A specimen is a branch component: {@code new X(branch, { leaf, say })} on a sub-branch the
 * caller made, {@code say(words)} told what the component did. It offers {@code root};
 * {@code extent(axis, v)} for each axis its leaf varies along - "colour", "size", "aspect" -
 * from −1 to 1; {@code key(ev)} for the keys its holder hands on, true when taken; and
 * {@code dispose()}.</p>
 */
public record HouseSpecimensModule() implements DomModule<HouseSpecimensModule>, SelfContent {

    public static final HouseSpecimensModule INSTANCE = new HouseSpecimensModule();

    public record HOUSE_SPECIMENS() implements Exportable._Constant<HouseSpecimensModule> {}

    public record HOUSE_PENDING() implements Exportable._Constant<HouseSpecimensModule> {}

    public record HOUSE_UNREALIZED() implements Exportable._Constant<HouseSpecimensModule> {}

    @Override
    public ImportsFor<HouseSpecimensModule> imports() {
        var b = ImportsFor.<HouseSpecimensModule>builder();
        var classes = new LinkedHashSet<ModuleImports<?>>();
        for (Specimen s : HouseSpecimens.INSTANCE.specimens()) classes.add(s.constructs());
        for (ModuleImports<?> c : classes) b.add(c);
        return b.build();
    }

    @Override
    public ExportsOf<HouseSpecimensModule> exports() {
        return new ExportsOf<>(INSTANCE, List.of(new HOUSE_SPECIMENS(), new HOUSE_PENDING(), new HOUSE_UNREALIZED()));
    }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        var house = HouseSpecimens.INSTANCE;
        String specimens = house.specimens().stream()
                .map(s -> "\"" + s.leaf().token() + "\": " + s.className())
                .collect(Collectors.joining(", "));
        String pending = house.pending().stream().map(c -> "\"" + c.token() + "\"").collect(Collectors.joining(", "));
        String unrealized = house.unrealized().stream().map(c -> "\"" + c.token() + "\"").collect(Collectors.joining(", "));
        return List.of(
                "// Generated by HouseSpecimensModule from HouseSpecimens - do not hand-edit: the class that builds each leaf live.",
                "const HOUSE_SPECIMENS = Object.freeze({ " + specimens + " });",
                "// Realized, their specimens still to come.",
                "const HOUSE_PENDING = Object.freeze([" + pending + "]);",
                "// Realized by nothing yet.",
                "const HOUSE_UNREALIZED = Object.freeze([" + unrealized + "]);");
    }
}
