package hue.captains.singapura.js.homing.ui.controlpanel;

import hue.captains.singapura.js.homing.component.taxonomy.Component;
import hue.captains.singapura.js.homing.component.taxonomy.Taxonomy;
import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.ui.controllability.ControlCatalogue;
import hue.captains.singapura.js.homing.ui.controllability.ControlOption;
import hue.captains.singapura.js.homing.ui.controllability.ControlType;
import hue.captains.singapura.js.homing.ui.controllability.HouseControllability;
import hue.captains.singapura.js.homing.ui.controllability.WithExtent;
import hue.captains.singapura.js.homing.ui.controllability.WithSwitch;
import hue.captains.singapura.js.homing.ui.taxonomy.HouseTaxonomy;

import java.util.List;
import java.util.stream.Collectors;

/**
 * The house's controllability as a page has it, generated from {@link HouseControllability} - so no
 * second list can drift from it:
 *
 * <ul>
 *   <li>{@code CONTROL_OPTIONS[option]} - every option of the catalogue, in its order:
 *       {@code { category, means, rest, method, label }} - {@code means} one of {@code extent},
 *       {@code switch}, {@code action}, {@code question}; {@code rest} a number for a degree, a
 *       truth for a switch, null otherwise;</li>
 *   <li>{@code CONTROL_TYPES[type]} - the options each control type takes, in order;</li>
 *   <li>{@code CONTROL_TYPE_OF[leaf]} - every leaf of the house's taxonomy, by its token, and its
 *       control type, found up its lineage.</li>
 * </ul>
 */
public record ControlCatalogueModule() implements EsModule<ControlCatalogueModule>, SelfContent {

    public static final ControlCatalogueModule INSTANCE = new ControlCatalogueModule();

    public record CONTROL_OPTIONS() implements Exportable._Constant<ControlCatalogueModule> {}

    public record CONTROL_TYPES() implements Exportable._Constant<ControlCatalogueModule> {}

    public record CONTROL_TYPE_OF() implements Exportable._Constant<ControlCatalogueModule> {}

    @Override public ImportsFor<ControlCatalogueModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<ControlCatalogueModule> exports() {
        return new ExportsOf<>(INSTANCE, List.of(new CONTROL_OPTIONS(), new CONTROL_TYPES(), new CONTROL_TYPE_OF()));
    }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        var house = HouseControllability.INSTANCE;
        ControlCatalogue catalogue = house.catalogue();
        String options = catalogue.options().stream()
                .map(o -> quoted(o.name().value()) + ": Object.freeze({ category: " + quoted(catalogue.parent(o).name().value())
                        + ", means: " + quoted(o.means()) + ", rest: " + rest(o) + ", method: " + quoted(o.method())
                        + ", label: " + quoted(o.label()) + " })")
                .collect(Collectors.joining(",\n    "));
        List<ControlType> all = house.classification().types();
        String types = all.stream()
                .map(t -> quoted(t.name()) + ": Object.freeze([" + t.options().stream().map(o -> quoted(o.name().value())).collect(Collectors.joining(", ")) + "])")
                .collect(Collectors.joining(",\n    "));
        Taxonomy taxonomy = HouseTaxonomy.INSTANCE.read();
        String typeOf = taxonomy.components().stream()
                .map((Component<?> c) -> quoted(c.token()) + ": " + quoted(house.findControlType(taxonomy, c).name()))
                .collect(Collectors.joining(",\n    "));
        return List.of(
                "// Generated by ControlCatalogueModule from HouseControllability - do not hand-edit.",
                "// Every option: what it is filed under, how it is controlled, where it rests, the method that applies it, its words.",
                "const CONTROL_OPTIONS = Object.freeze({\n    " + options + "\n});",
                "// Every control type: the options it takes, beyond the axes a component varies along.",
                "const CONTROL_TYPES = Object.freeze({\n    " + types + "\n});",
                "// Every leaf of the house's taxonomy, and its control type.",
                "const CONTROL_TYPE_OF = Object.freeze({\n    " + typeOf + "\n});");
    }

    /** Where an option rests, as a page has it: a number for a degree, a truth for a switch, null for what is done or asked. */
    private static String rest(ControlOption<?> o) {
        return switch (o) {
            case WithExtent<?> e -> e.rest() == Math.rint(e.rest()) ? String.valueOf((long) e.rest()) : String.valueOf(e.rest());
            case WithSwitch<?> s -> String.valueOf(s.rest());
            default -> "null";
        };
    }

    private static String quoted(String s) { return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""; }
}
